// Generated by scripts/generate-dev-kiosk-routes.mjs — do not edit by hand.

export const DEV_KIOSK_APP_ROUTES = [
  "/",
  "/dev-datafetching",
  "/dev-three-panel",
  "/message-debug",
  "/solid-bg-test",
] as const;

export type DevKioskAppRoute = (typeof DEV_KIOSK_APP_ROUTES)[number];
