// Generated by scripts/generate-dev-kiosk-routes.mjs — do not edit by hand.

export const DEV_KIOSK_APP_ROUTES = [
  "/",
  "/dev-datafetching",
  "/dev-message-debugger",
  "/dev-three-panel-layout",
] as const;

export type DevKioskAppRoute = (typeof DEV_KIOSK_APP_ROUTES)[number];
